### PR TITLE
Clean up code and add nickname support

### PR DESCRIPTION
**Pull request by Sciguymjm**
Feel free to comment and let me know what the status is.

### CODE REVIEW

**Comment by NorbiPeti** [comment]
Thanks for the nicknames and the cleanup. Btw, will Essentials update the config file as soon as one uses /nick?

**Comment by Sciguymjm** [comment]
Yes, it does.

**Comment by Sciguymjm** [comment]
Although to update the HashMap of nicknames you need to have the person relog.

**Comment by NorbiPeti** [comment]
Yeah, I saw it. :P

**Pull request merged**
